### PR TITLE
Partial version support

### LINKED ISSUE #15: Mixlib::Versioning.parse fails to create proper OpscodeSemVer object
Mixlib::Versioning.parse('0.4') should yield the same result as Mixlib::Versioning.parse('0.4.0').  As well as Mixlib::Versioning.parse('1') should equal to Mixlib::Versioning.parse('1.0.0').  Rather the parse is returning nil.

### PR DESCRIPTION
**Pull request by rhass**
This adds support for partial version strings to the RubyGems version type to more closely imitate the Gem::Version behavior.

This PR also fixes a bug when comparing Rubygems version types against `semver` or `opscode_semver` in which the value of `iteration` was always assigned to `0` which would result in incorrect comparison results. We also now correctly parse git style version strings when the rubygems formatter is specified and reject the git hash. This replicates the `Gem::Version.new` behavior more closely but in a more usable form.

- Fixes #15

What this PR does not do:
- Add partial version support to `opscode_semver`
- Add partial version support to `semver` (violates semver anyway)

The following items will be addressed in a different PR:
- Add pessimistic operator support `>~`
- Add `satisfies?`

/cc @chef/engineering-services

### CODE REVIEW

File: lib/mixlib/versioning/format/rubygems.rb [hunk 1]
```diff
@@ -41,23 +45,56 @@ class Format
...
-          match = version_string.match(RUBYGEMS_REGEX) rescue nil
+          # Pure regex along will never match partial versions correctly in the
+          # expected groupings. This is becausel partial versions shift the
+          # grouping values and break the mappings to for each appropriate value.
+          rubygems_version = version_string.scan(/[0-9]+|[a-z]+/i).map do |s|
+            /^\d+$/ =~ s ? s.to_i : s
+          end rescue nil
+
+          # Each value for MAJOR.MINOR.PATCH must be a integer.
+          unless rubygems_version && rubygems_version[0..2].map {|v| v.is_a?(Integer) }.all?
```
Comment (wrightp) [inline lib/mixlib/versioning/format/rubygems.rb]: `unless rubygems_version` is a no op when rubygems_version is an empty array . I don't think that's what we want here. Maybe? Unit test coverage should verify that.

This would only happen the method was passed nil, empty string or something we don't really expect (which I am not sure if that's already been handled before getting to this point).

Just a personal preference, I've also found using `unless` blocks with multiple conditions to use more brain power than simply making each condition contained.

File: lib/mixlib/versioning/format/rubygems.rb [hunk 2]
```diff
@@ -41,23 +45,56 @@ class Format
...
+            raise_invalid_version(version_string)
+          end
 
-          unless match
-            raise Mixlib::Versioning::ParseError, "'#{version_string}' is not a valid #{self.class} version string!"
+          if version_string =~ /\-\D+/
```
Comment (wrightp) [inline lib/mixlib/versioning/format/rubygems.rb]: Per comment above... execute this first and it should simply the `unless #all?` condition.

File: lib/mixlib/versioning/format/rubygems.rb [hunk 3]
```diff
@@ -41,23 +45,56 @@ class Format
...
+            raise_invalid_version(version_string)
           end
 
-          @major, @minor, @patch, @prerelease, @iteration = match[1..5]
-          @major, @minor, @patch, @iteration = [@major, @minor, @patch, @iteration].map(&:to_i)
+          @major, @minor, @patch = rubygems_version[0..2]
+          @major, @minor, @patch = [ @major, @minor, @patch ].map(&:to_i)
```
Comment (wrightp) [inline lib/mixlib/versioning/format/rubygems.rb]: Haven't these already been verified to all be Integers?

File: lib/mixlib/versioning/format/rubygems.rb (hunk 1 above)
Comment (tduffield) [inline lib/mixlib/versioning/format/rubygems.rb]: Do we have a test for an empty string? If not, would be easy to add one. We could also enforce type to ensure that we aren't passed nil or a non-valid type (like Float).

**Comment by rhass** [comment]
The default use case for partial is not working properly.
Eg:
```
Mixlib::Versioning.parse('12.34')
=> nil
```

Specifying `:partial` works, but it should not be required.

**Comment by rhass** [comment]
Fixed the default use case problem.

File: lib/mixlib/versioning/format/partial.rb [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+      # --------
+      # ```text
+      # 11
+      # 11.0
+      # ```
+      #
+      # @author Seth Chisamore (<schisamo@chef.io>)
+      # @author Christopher Maier (<cm@chef.io>)
+      # @author Ryan Hass (<rhass@chef.io>)
+      class Partial < Format
```
Comment (schisamo) [inline lib/mixlib/versioning/format/partial.rb]: Let's call this `PartialSemVer`.

File: lib/mixlib/versioning/format/partial.rb [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+
+          unless match
+            raise Mixlib::Versioning::ParseError, "'#{version_string}' is not a valid #{self.class} version string!"
+          end
+
+          @major, @minor = match[1..2]
+          @major, @minor = [@major, @minor].map(&:to_i)
+
+          # Partial versions do not contain these values, so we just set them to nil.
+          @patch      = nil
```
Comment (schisamo) [inline lib/mixlib/versioning/format/partial.rb]: I think we actually want to set `@patch` to 0 (and `@minor` to 0 if only a `@major` is provided) so that comparisons between `1`, `1.0` and `1.0.0` are all equal.

File: README.md [hunk 6]
```diff
@@ -122,6 +122,23 @@ Examples of valid Git Describe version strings:
...
+
+## SemVer Partial
+
+
+```text
+MAJOR
+MAJOR.MINOR
+```
+
+Examples of vali SemVer Partial version strings:
```
Comment (tduffield) [inline README.md]: valid
